### ISSUE TITLE
South Korea Address Data Help

### ISSUE THREAD

**Issue by justinelliotmeyers** [DevLeti/englishaddress#1]
Hey! can you assist me with questions I have about south korea address data? Thanks!

**Comment by DevLeti** [comment]
> Hey! can you assist me with questions I have about south korea address data? Thanks!

Yes. Leave your questions here!

**Comment by justinelliotmeyers** [comment]
Really appreciate your help!
I need to find the most current, best resolution 
and friendly copyright main download for three datasets, which I believe the links are below. I need address points, building polygons and cadastral parcels. Can you confirm these are the best way to download these datasets?
addresses: https://business.juso.go.kr/addrlink/main.do
buildings: https://www.data.go.kr/data/15052097/fileData.do
parcels: https://www.data.go.kr/data/15045882/fileData.do

**Comment by DevLeti** [comment]
> Really appreciate your help! I need to find the most current, best resolution and friendly copyright main download for three datasets, which I believe the links are below. I need address points, building polygons and cadastral parcels. Can you confirm these are the best way to download these datasets? addresses: https://business.juso.go.kr/addrlink/main.do buildings: https://www.data.go.kr/data/15052097/fileData.do parcels: https://www.data.go.kr/data/15045882/fileData.do


1. addresses: yes. You can get addresses in Korea with Korean and English.
2. buildings: [check here - juso.go.kr](https://business.juso.go.kr/addrlink/elctrnMapProvd/geoDBDwldList.do?menu=%EB%8F%84%EB%A1%9C%EB%AA%85%EC%A3%BC%EC%86%8C%20%EC%A0%84%EC%9E%90%EC%A7%80%EB%8F%84#this) '도로명주소 전자지도' will help you I think.
3. Probably yes. I don't know well about cadastral parcels. but there is 'cadastral parcels' in API name, so I think it can help you.
Have nice day!

**Comment by justinelliotmeyers** [comment]
This is perfect!! 
I believe https://business.juso.go.kr/addrlink/elctrnMapProvd/geoDBDwldList.do?menu=%EB%8F%84%EB%A1%9C%EB%AA%85%EC%A3%BC%EC%86%8C%20%EC%A0%84%EC%9E%90%EC%A7%80%EB%8F%84#this has a little bit of everything. There is a download all part, but I am currently not in South Korea.

I'd like to get an updated version of the address point data in openaddresses as well as the building footprints. 

I'll close this issue, but if you could assist with getting the data, would love to chat further in email (just sent).

Appreciate your time and help!
Justin

**Comment by DevLeti** [comment]
> This is perfect!! I believe https://business.juso.go.kr/addrlink/elctrnMapProvd/geoDBDwldList.do?menu=%EB%8F%84%EB%A1%9C%EB%AA%85%EC%A3%BC%EC%86%8C%20%EC%A0%84%EC%9E%90%EC%A7%80%EB%8F%84#this has a little bit of everything. There is a download all part, but I am currently not in South Korea.
> 
> I'd like to get an updated version of the address point data in openaddresses as well as the building footprints.
> 
> I'll close this issue, but if you could assist with getting the data, would love to chat further in email (just sent).
> 
> Appreciate your time and help! Justin

No worry! I will reply to you within 48 hours.
